steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/vivkvecv/kafdrop.git'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - '/src/'
      - 'vivkdeep@test:/home/vivkdeep/'
      - '--zone' 
      - 'asia-south1-a'
      
options:
  logging: CLOUD_LOGGING_ONLY
