steps:    
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - './src/'
      - 'vivkdeep@test2:/home/vivkdeep/test1'
      - '--zone' 
      - 'asia-south1-c'
      - '--project'
      - 'my-second-project-442218'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'vivkdeep@test2'
      - '--zone' 
      - 'asia-south1-c'
      - '--project'
      - 'my-second-project-442218'
      - '--command'
      - 'mkdir /home/vivkdeep/test && mkdir /home/vivkdeep/test2'
      
options:
  logging: CLOUD_LOGGING_ONLY
