steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - './kafdrop/'
      - 'vivkdeep@test:/home/vivkdeep/'
      - '--zone' 
      - 'asia-south1-a'
      
options:
  logging: CLOUD_LOGGING_ONLY
