steps:    
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing files in the current directory:"
        ls -la
        
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - './*.*'
      - 'vivkdeep@test2:/home/vivkdeep/test'
      - '--zone' 
      - 'asia-south1-c'
      - '--project'
      - 'my-second-project-442218'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'vivkdeep@test2'
      - '--zone' 
      - 'asia-south1-c'
      - '--project'
      - 'my-second-project-442218'
      - '--command'
      - 'mkdir /home/vivkdeep/test2 && mkdir /home/vivkdeep/test3'
      
options:
  logging: CLOUD_LOGGING_ONLY
