name: kafdrop
on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/test.yaml'
jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Maven
  # uses: stCarolas/setup-maven@417e1a9899611c0350621d1fb0c2770f35105c69vecv-streamer-0.0.1-SNAPSHOT.jar
      uses: stCarolas/setup-maven@v4.4
      with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0....
        maven-version: 3.8.2
    - name: Build
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven and push to vm
      run: mvn -B package
    - name: print
      run: |
        docker build -t jp.icr.io/sa-vecv-dev/kafdrop:10.04.02 .
        docker images
    - name: Login to IKS
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry
        ibmcloud login -a cloud.ibm.com -r jp-tok -g Default --apikey 7lqHpatPKWUqcx1yZfLIG8Gw0ymeZ1CXTGOG9O_DXj4C
        ibmcloud cr region-set jp-tok
        ibmcloud cr login
        docker push jp.icr.io/sa-vecv-dev/kafdrop:10.04.02
